services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: # Load the env file in the system container environment
      - ../.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  postgres_data: